### ISSUE TITLE
Integration no longer works. Setup error, trying again: Check the logs

### ISSUE THREAD

**Issue by FloX5E70** [erikkastelec/hass-WEM-Portal#110] opened 2024-11-08 14:00 UTC
Everything worked until the day before yesterday. Access to the WEM portal works. Neither web nor API mode works. The similarly structured IO broker integration continues to work.
Thanks for help and the developer of this integration and shame on Weishaupt for the bad open samrthome support/no API.

Debug info:

`The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/wemportal/coordinator.py", line 47, in _async_update_data
    x = await self.hass.async_add_executor_job(self.api.fetch_data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wemportal/wemportalapi.py", line 142, in fetch_data
    raise WemPortalError from exc
custom_components.wemportal.exceptions.WemPortalError
2024-11-08 14:43:00.613 ERROR (MainThread) [custom_components.wemportal] Error fetching data from wemportal
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 195, in api_login
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.wemportal.com/app/Account/Login

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 88, in fetch_data
    self.api_login()
  File "/config/custom_components/wemportal/wemportalapi.py", line 208, in api_login
    raise ForbiddenError(
custom_components.wemportal.exceptions.ForbiddenError: WemPortal forbidden error: Server returned internal status code:  and message: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/wemportal/coordinator.py", line 67, in _async_update_data
    x = await self.hass.async_add_executor_job(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wemportal/wemportalapi.py", line 142, in fetch_data
    raise WemPortalError from exc
custom_components.wemportal.exceptions.WemPortalError
2024-11-08 14:43:00.616 DEBUG (MainThread) [custom_components.wemportal] Finished fetching WemPortal update data in 0.238 seconds (success: False)`

**Comment by dm82m** [comment] 2024-11-08 14:10
Duplicate or #96

**Comment by tennet** [comment] 2024-11-11 08:19
File "/config/custom_components/wemportal/wemportalapi.py", line 142, in fetch_data
    raise WemPortalError from exc
custom_components.wemportal.exceptions.WemPortalError
2024-11-11 09:18:08.289 WARNING (MainThread) [custom_components.wemportal] Creating new wemportal api instance
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 195, in api_login
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.wemportal.com/app/Account/Login
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 88, in fetch_data
    self.api_login()
  File "/config/custom_components/wemportal/wemportalapi.py", line 208, in api_login
    raise ForbiddenError(
custom_components.wemportal.exceptions.ForbiddenError: WemPortal forbidden error: Server returned internal status code:  and message: 
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/wemportal/coordinator.py", line 47, in _async_update_data
    x = await self.hass.async_add_executor_job(self.api.fetch_data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wemportal/wemportalapi.py", line 142, in fetch_data
    raise WemPortalError from exc
custom_components.wemportal.exceptions.WemPortalError
2024-11-11 09:18:08.533 ERROR (MainThread) [custom_components.wemportal] Error fetching data from wemportal
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 195, in api_login
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.wemportal.com/app/Account/Login
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 88, in fetch_data
    self.api_login()
  File "/config/custom_components/wemportal/wemportalapi.py", line 208, in api_login
    raise ForbiddenError(
custom_components.wemportal.exceptions.ForbiddenError: WemPortal forbidden error: Server returned internal status code:  and message: 
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/wemportal/coordinator.py", line 67, in _async_update_data
    x = await self.hass.async_add_executor_job(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wemportal/wemportalapi.py", line 142, in fetch_data
    raise WemPortalError from exc
custom_components.wemportal.exceptions.WemPortalError

**Comment by newslettersns2000** [comment] 2024-11-12 00:32
same problem, no data since 10th November , Smartphone app/Wem working but very slow , webportal ok,

**Comment by ErazorVIP** [comment] 2024-11-13 09:11
same Problem, cant login with integration in Home Assistant but webportal and smartphone app ok

**Comment by WallyGER** [comment] 2024-11-13 17:05
I have the same problem!

**Comment by newslettersns2000** [comment] 2024-11-15 23:23
I wrote to Weishaupt., let's see what happens

**Comment by dm82m** [comment] 2024-11-16 06:31
Guys this is a duplicate of #96 

communication with Weishaupt has already happened. Check the linked issue for details.

**Comment by newslettersns2000** [comment] 2024-11-19 22:35
For me, everything works fine again since yesterday 5 PM till now

**Comment by erikkastelec** [comment] 2024-11-20 20:59
Duplicate of #96

**Closed** 2024-11-20 20:58 UTC
