### ISSUE TITLE
Einrichtung fehlgeschlagen, wird erneut überprüft: Überprüfe die Protokolle

### ISSUE THREAD

**Issue by Uwe1960** [erikkastelec/hass-WEM-Portal#97] opened 2024-10-03 15:14 UTC
The problem already occurred in HA 2024.9.x, disappeared every time after a few restarts of HA. With the transition to HA 2024.10.0, the problem no longer disappears even after several restarts of HA or several “reloads” of Weishaupt WEM Portal. Going back to HA 2024.9.3 has not solved the problem.

**Comment by Karo-X** [comment] 2024-10-03 21:51
Then it would be helpful if you could share the information from the protocol with us. I suspect it is the same error as already reported in #96(?).

**Comment by dm82m** [comment] 2024-10-04 06:25
It is not a Home Assistant version related issue. The issue is caused by changes Weishaupt made to their portal.

**Comment by misterbond007** [comment] 2024-10-04 11:06
I have the same problem.
Log file:
`Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 254, in make_api_call
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.wemportal.com/app/device/Read`

**Comment by Hoost24** [comment] 2024-10-06 15:45
Same for me

**Comment by developer-stephan** [comment] 2024-10-06 17:12
> Same for me

The solution: https://github.com/erikkastelec/hass-WEM-Portal/issues/96

**Comment by erikkastelec** [comment] 2024-10-06 20:40
Fix has been released in the newest version (1.5.10)

**Closed by erikkastelec** 2024-10-06 20:40 UTC
